times = ("São Paulo","Flamengo","Internacional","Grêmio","Atlético-MG","Palmeiras","Corinthians","Cruzeiro","Fluminense","América-MG","Botafogo","Sport","Vasco","Vitória","Bahia","Chapecoense","Santos","Atlético-PR","Ceará","Paraná")
print("Os cinco primeiros times são:")
print(times[0:5])
print("Os últimos quatro colocados são:")
print(times[16:20])
print("Os times em ordem alfabética são:")
print(sorted(times))
print("A Chapecoense está na posição:")
x = times.index("Chapecoense")
print(x)
